@WebAPI_HostAddress = https://localhost:7214

GET {{WebAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{WebAPI_HostAddress}}/api/user
Content-Type: application/json

{
  //UserModel
}

###
